config/routes.rb
# @Author: Ronnie Nyaga <Ronnie>
# @Date:   2016-06-11T20:28:57+03:00
# @Email:  ronnienyaga@gmail.com
# @Last modified by:   Ronnie
# @Last modified time: 2016-06-13T16:59:19+03:00



Rails.application.routes.draw do
  devise_for :users
  resources :recipes do
    get :autocomplete_l_ingredient_name, :on => :collection
    get :autocomplete_serving_type_name, :on => :collection
  end

  root 'recipes#index'
end

app/models/l_ingredient.rb
# @Author: Ronnie Nyaga <Ronnie>
# @Date:   2016-06-11T22:22:54+03:00
# @Email:  ronnienyaga@gmail.com
# @Last modified by:   Ronnie
# @Last modified time: 2016-06-12T00:13:19+03:00



class LIngredient < ActiveRecord::Base
  
end

app/models/recipe.rb
# @Author: Ronnie Nyaga <Ronnie>
# @Date:   2016-06-11T20:28:57+03:00
# @Email:  ronnienyaga@gmail.com
# @Last modified by:   Ronnie
# @Last modified time: 2016-06-13T17:12:02+03:00



class Recipe < ActiveRecord::Base

  belongs_to :user
  has_many :recipe_ingredients
  has_many :recipe_steps
  has_many :serving_types

  accepts_nested_attributes_for   :recipe_ingredients,
                                  # reject_if: proc { |attributes| attributes['ingredient_id'].blank? },
                                  allow_destroy: true

  accepts_nested_attributes_for   :recipe_steps,
                                  reject_if: proc { |attributes| attributes['step'].blank? },
                                  allow_destroy: true

  validates :name, :preptime, :authorsTip, :servings, :price, :story, presence: true

  has_attached_file :cover, styles: { medium: "400x400#"}
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/

end

app/models/recipe_ingredient.rb
# @Author: Ronnie Nyaga <Ronnie>
# @Date:   2016-06-11T20:28:57+03:00
# @Email:  ronnienyaga@gmail.com
# @Last modified by:   Ronnie
# @Last modified time: 2016-06-12T00:58:19+03:00



class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe_step.rb
# @Author: Ronnie Nyaga <Ronnie>
# @Date:   2016-06-11T20:28:57+03:00
# @Email:  ronnienyaga@gmail.com
# @Last modified by:   Ronnie
# @Last modified time: 2016-06-11T21:27:27+03:00



class RecipeStep < ActiveRecord::Base
  belongs_to :recipe

end

app/models/serving_type.rb
# @Author: Ronnie Nyaga <Ronnie>
# @Date:   2016-06-13T16:55:02+03:00
# @Email:  ronnienyaga@gmail.com
# @Last modified by:   Ronnie
# @Last modified time: 2016-06-13T16:55:45+03:00



class ServingType < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
# @Author: Ronnie Nyaga <Ronnie>
# @Date:   2016-06-11T20:28:57+03:00
# @Email:  ronnienyaga@gmail.com
# @Last modified by:   Ronnie
# @Last modified time: 2016-06-14T16:14:35+03:00



class RecipesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  before_action :set_recipe, only: [:edit, :show, :update, :destroy]

  autocomplete :l_ingredient, :name
  autocomplete :serving_type, :name

  def index
    @recipes = Recipe.all.order('dateCreated DESC')
  end

  def show

  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    params[:recipe][:recipe_ingredients_attributes].map { |k, v|
      # Find or create the ingredient and return id
      v["ingredient_id"] = LIngredient.find_or_create_by(name: v["ingredient"]).id
    }
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: "Successfully created new recipe"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    # return render json: params[:recipe][:serving_type]
    ServingType.find_or_create_by(name: params[:recipe][:serving_type])
    params[:recipe][:recipe_ingredients_attributes].map { |k, v|
      # Find or create the ingredient and return id
      v["ingredient_id"] = LIngredient.find_or_create_by(name: v["ingredient"]).id
    }
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: "Successfully deleted recipe"
  end


  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(
      :name, :preptime, :authorsTip, :servings, :serving_type_id, :serving_type,
      :price, :story, :cover, :tags,
      recipe_ingredients_attributes: [:id, :ingredient_id, :ingredient, :quantity, :measure, :_destroy],
      recipe_steps_attributes: [:id, :step, :_destroy]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Pika
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-brand= link_to "Pika", root_path

        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to current_user.email, edit_user_registration_path
            %li= link_to "New Recipe", new_recipe_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            %li= link_to "Login", new_user_session_path
            %li= link_to "Sign Up", new_user_registration_path

    .container.main_content
      - flash.each do |name,msg|
        = content_tag :div, msg, class: "alert"
      = yield

app/views/recipes/_form.html.haml
= simple_form_for(@recipe, html: { multipart: true }) do |f|
  - if @recipe.errors.any?
    #errors
      %p
      = pluralize(@recipe.errors.count, 'error')
      Prevented this recipe from saving
    %ul
      - @recipe.errors.full_messages.each do |msg|
        %li= msg
  -# :name, :preptime, :authorsTip, :servings, :servingTypeID, :price, :story
  .panel-body
    .row
      .col-md-6
        = f.hidden_field :serving_type_id, :id => 'serving_type_id'
        = f.input :name, input_html: {class: 'form-control'}
        = f.input :preptime, input_html: {class: 'form-control'}
        = f.label :serving_type
        = f.autocomplete_field :serving_type, autocomplete_serving_type_name_recipes_path, class: "form-control", :id_element => '#serving_type_id'
        = f.input :servings, input_html: {class: 'form-control'}
        = f.input :price, input_html: {class: 'form-control'}
        = f.input :cover, input_html: {class: 'form-control'}
      .col-md-6
        = f.input :story, input_html: {class: 'form-control', rows: 6}
        = f.label :authorsTip
        = f.text_area :authorsTip, class: 'form-control', rows: 5
        = f.input :tags, input_html:{class: 'form-control', data: {role:'tagsinput'}}


    .row
      .col-md-12
        %h3 Ingredients
        #ingredients
          = f.simple_fields_for :recipe_ingredients do |recipe_ingredient|
            = render 'recipe_ingredient_fields', f: recipe_ingredient
          .links
            = link_to_add_association 'Add Ingredient', f, :recipe_ingredients, class: "btn btn-default add-button"

      .col-md-12
        %h3 Directions
        #directions
          = f.simple_fields_for :recipe_steps do |recipe_step|
            = render 'recipe_step_fields', f: recipe_step
          .links
            = link_to_add_association 'Add Step', f, :recipe_steps, class: "btn btn-default add-button"


  = f.button :submit, class: "btn btn-primary"

app/views/recipes/_recipe_ingredient_fields.html.haml
.form-inline.clearfix
  .nested-fields
    .row
      .col-md-3
        = f.hidden_field :ingredient_id, :id => 'ingredient_id'
        = f.autocomplete_field :ingredient, autocomplete_l_ingredient_name_recipes_path, class: "form-input form-control", :id_element => '#ingredient_id'
        %label Ingredient
      .col-md-3
        -# = f.input :ingredient_id, input_html: { class: "form-input form-control" }
        = f.input :quantity, input_html: { class: "form-input form-control" }
      .col-md-3
        = f.input :measure, input_html: { class: "form-input form-control" }
      .col-md-3
        = link_to_remove_association "Remove", f, class: "btn btn-default"

app/views/recipes/_recipe_step_fields.html.haml
.form-inline.clearfix
  .nested-fields
    .row
      .col-md-9
        = f.input :step, input_html: { class: "form-input form-control" }
      .col-md-3
        = link_to_remove_association "Remove", f, class: "btn btn-default"

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

app/views/recipes/index.html.haml
#recipes.transitions-enabled

  - @recipes.each do |recipe|
    .box.panel.panel-default
      = link_to (image_tag recipe.cover.url), recipe
      .panel-body
        %h2= link_to recipe.name, recipe
        %div.btn-group
          = link_to 'View', recipe, class: 'btn btn-default'
          - if user_signed_in?
            = link_to 'Edit', edit_recipe_path(recipe), class: 'btn btn-default'
            = link_to 'Delete', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default'
        %p.user
          Submitted by
          = recipe.user.email

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/show.html.haml
#recipe_top.row
  .col-md-4
    = image_tag @recipe.cover.url(:medium), class: "recipe_image"
  .col-md-8
    .row#recipe_info
      %h1= @recipe.name
      .col-md-7
        %p.text-justify= @recipe.story
        %h3 Author's Tip
        %p.text-justify= @recipe.authorsTip
        %p
          Submitted by
          = @recipe.user.email
      .col-md-5
        %p
          Preparation Time:
          = @recipe.preptime
          Minutes
        %p
          Servings:
          = pluralize(@recipe.servings, @recipe.serving_type)
        %p
          Price: Ksh.
          = @recipe.price
        %h2 Tags
        %p.text-justify
          - if @recipe.tags.nil?
            No tags have been specified
          - else
            - @recipe.tags.split(",").each do |tag|
              %span.label.label-info
                = tag

.row
  .col-md-12
    #ingredients
      %h2 Ingredients
      %table.table.table-hover
        %thead
          %tr
            %th
              Ingredient
            %th
              Quantity
            %th
              Measure
        %tbody
          - @recipe.recipe_ingredients.each do |ingredient|
            %tr
              %td= ingredient.ingredient
              %td= ingredient.quantity
              %td= ingredient.measure

  .col-md-12
    #directions
      %h2 Directions
      %ul
        - @recipe.recipe_steps.each do |step|
          %li= step.step

.row
  .col-md-12
    = link_to "Back", root_path, class: "btn btn-default"
    = link_to "Edit", edit_recipe_path, class: "btn btn-default"
    = link_to "Delete", recipe_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"